"""
Note that Claude was used to assist with writing this code.

Stochastic MPC scenario generators.

Three distributions — one per uncertain quantity — following Kumar et al.:

  1. LedoitWolfEstimator        (load)       — Sec. IV.B, p. 5
     Multivariate Gaussian over the 168-h week profile with shrinkage
     covariance Σ̃n = (b²/d²)·m·I + (a²/d²)·S so it stays full-rank
     when p > n.

  2. EmpiricalLogNormalSampler  (FR price)   — Sec. IV.C, p. 6
     "We have found that the FR price follows a log-normal distribution
      and has high variance ... we use the empirical log-normal
      distribution to generate FR price realizations."
     Fit μ_log = mean(log π_f), σ_log = std(log π_f); sample exp(N(μ, σ²)).

  3. EmpiricalGaussianSampler   (FR signal)  — Sec. IV.C, p. 6
     "The signal approximately follows a Gaussian distribution, which
      indicates that there is small temporal correlation ... realizations
      generated by sampling from the empirical Gaussian."
     Fit μ, σ from data; sample iid N(μ, σ²).

The bottom of the file validates each fit against the real data served
by data.py (Shapiro-Wilk / Anderson-Darling / K-S, moments, Q-Q plot).

See also:


Ledoit-Wolf details:

  Observations xk ∈ R^p (k=1..n) assumed drawn from a zero-mean
  distribution with unknown covariance Σn.  The sample covariance
  Sn = Xn Xn^T / n is rank-deficient here because p=168 (hours in a
  week) >> n=52 (weeks in one year of data).

  The paper shrinks Sn towards a scaled identity target:

      Σ*_n = ρ1 · I + ρ2 · Sn

  minimising E[||Σ*_n - Σn||²] under the scaled Frobenius norm
  ||A||² = Tr(A Aᵀ) / p (so that ||I_p||² = 1).  The optimal
  coefficients depend on unknown quantities of Σn and are replaced
  by bona-fide estimators:

      mn   = ⟨Sn, I⟩                              (sample diag-mean)
      d²n  = ||Sn - mn·I||²
      b̄²n  = (1/n²) Σ_k ||xk xkᵀ - Sn||²
      b²n  = min(b̄²n, d²n)
      a²n  = d²n - b²n

  Shrinkage estimator:

      Σ̃n = (b²n / d²n) · mn · I + (a²n / d²n) · Sn

  The weight b²n/d²n ∈ [0,1] is the shrinkage intensity (how much we
  pull towards the identity target).

We use this to model the *centered* week profile (raw load minus the
per-hour-of-week mean).  A scenario is drawn by sampling a p-dim
Gaussian with mean = weekly-mean-profile and covariance = Σ̃n; a slice
of that weekly scenario can then be served to the stochastic MPC
over its N-hour prediction horizon.
"""

from __future__ import annotations

import os

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

from data import load_dataset


# ─────────────────────────────────────────────────────────────────────────────
# Scaled Frobenius norm / inner product — paper's convention (p. 5)
# ─────────────────────────────────────────────────────────────────────────────
def sfrob_inner(A: np.ndarray, B: np.ndarray) -> float:
    """⟨A, B⟩ = Tr(A Bᵀ) / p."""
    p = A.shape[0]
    return float(np.einsum("ij,ij->", A, B) / p)


def sfrob_norm_sq(A: np.ndarray) -> float:
    """||A||² = Tr(A Aᵀ) / p, so that ||I_p||² = 1."""
    return sfrob_inner(A, A)


# ─────────────────────────────────────────────────────────────────────────────
# Reshape a long hourly series into weekly columns
# ─────────────────────────────────────────────────────────────────────────────
def reshape_to_weekly(y: np.ndarray, hours_per_sample: int = 168) -> np.ndarray:
    """
    Return X of shape (p, n) where p = hours_per_sample and n = T // p.
    Each column is a consecutive, non-overlapping weekly profile.
    Trailing hours that don't fill a full week are discarded.
    """
    T = y.size
    n = T // hours_per_sample
    assert n >= 2, f"need >=2 full weeks, got T={T}"
    return y[: n * hours_per_sample].reshape(n, hours_per_sample).T


# ─────────────────────────────────────────────────────────────────────────────
# Ledoit-Wolf shrinkage estimator
# ─────────────────────────────────────────────────────────────────────────────
class LedoitWolfEstimator:
    """
    Fit a shrinkage covariance to a (p × n) data matrix whose columns are
    i.i.d. draws of the p-dim random vector.  The sample mean is removed
    (paper assumes mean-zero data) and stored as `mean_` so that samples
    can be returned in the original (non-centered) scale.

    Attributes after fit
    --------------------
    p, n                  : dimensions
    mean_                 : (p,)      sample mean profile
    S                     : (p,p)    sample covariance on centered data
    Sigma                 : (p,p)    shrinkage estimator Σ̃n
    m, d2, b2_bar, b2, a2 : the scalar estimators from the paper
    shrinkage_intensity   : b2/d2 ∈ [0,1]  (weight on identity target)
    """

    def __init__(self):
        self.p = None
        self.n = None

    def fit(self, X: np.ndarray) -> "LedoitWolfEstimator":
        assert X.ndim == 2, "X must be (p, n)"
        p, n = X.shape
        self.p, self.n = p, n

        # Center: paper's formulae assume E[x] = 0
        self.mean_ = X.mean(axis=1)
        Xc = X - self.mean_[:, None]

        # Sample covariance (paper uses n, not n-1)
        S = (Xc @ Xc.T) / n
        self.S = S

        # Scalar estimators — all in the scaled Frobenius metric.
        I_p = np.eye(p)
        m = sfrob_inner(S, I_p)                       # E[m] → μn
        d2 = sfrob_norm_sq(S - m * I_p)               # E[d2] → δ²n

        # b̄²n = (1/n²) Σ_k ||xk xkᵀ − S||²
        # Vectorise by noting each xk xkᵀ is a rank-1 pxp matrix.
        b2_bar = 0.0
        for k in range(n):
            xk = Xc[:, k]
            outer_minus_S = np.outer(xk, xk) - S
            b2_bar += sfrob_norm_sq(outer_minus_S)
        b2_bar /= (n * n)

        b2 = min(b2_bar, d2)                          # E[b2] → β²n
        a2 = d2 - b2                                  # E[a2] → α²n

        # Shrinkage weights
        w_id = b2 / d2 if d2 > 0 else 1.0             # towards m·I
        w_s  = a2 / d2 if d2 > 0 else 0.0             # towards S

        self.m, self.d2 = m, d2
        self.b2_bar, self.b2, self.a2 = b2_bar, b2, a2
        self.shrinkage_intensity = w_id
        self.Sigma = w_id * m * I_p + w_s * S

        # Ensure symmetry (numerical hygiene before Cholesky)
        self.Sigma = 0.5 * (self.Sigma + self.Sigma.T)
        return self

    # ───────── Sampling ─────────────────────────────────────────────────
    def _chol(self) -> np.ndarray:
        """Cholesky factor with adaptive jitter for numerical SPD robustness."""
        p = self.p
        jitter = 1e-10 * max(np.trace(self.Sigma) / p, 1.0)
        for _ in range(10):
            try:
                return np.linalg.cholesky(self.Sigma + jitter * np.eye(p))
            except np.linalg.LinAlgError:
                jitter *= 10
        raise np.linalg.LinAlgError("Sigma not SPD even with jitter")

    def sample(self, n_scenarios: int, seed: int | None = None) -> np.ndarray:
        """
        Draw n_scenarios profiles from N(mean_, Sigma).
        Returns array of shape (p, n_scenarios).
        """
        rng = np.random.default_rng(seed)
        L = self._chol()
        Z = rng.standard_normal(size=(self.p, n_scenarios))
        return self.mean_[:, None] + L @ Z

    def sample_horizon(
        self,
        hour_of_week_start: int,
        horizon: int,
        n_scenarios: int,
        seed: int | None = None,
    ) -> np.ndarray:
        """
        Convenience for stochastic MPC: draw n_scenarios weekly profiles,
        then slice each one starting at `hour_of_week_start` for `horizon`
        hours (wrapping around the week if needed).
        Returns (horizon, n_scenarios).
        """
        assert 0 <= hour_of_week_start < self.p
        full = self.sample(n_scenarios=n_scenarios, seed=seed)      # (p, S)
        idx = (hour_of_week_start + np.arange(horizon)) % self.p    # (horizon,)
        return full[idx, :]


# ─────────────────────────────────────────────────────────────────────────────
# Seasonally-adjusted Ledoit-Wolf  — fixes non-stationary annual drift
# ─────────────────────────────────────────────────────────────────────────────
#
# A flat LW fit on 52 weeks of a *non-stationary* series (campus load) fails
# because the 52 "samples" are not i.i.d.: they contain a strong seasonal
# drift (e.g. here the weekly mean moves from 10 MW in winter to 17 MW in
# summer, contributing ~48% of total variance).  The sample covariance then
# includes a giant "shift the whole week up or down" eigen-direction, which
#   (a) inflates scenario variance (each sample gets a random seasonal shift),
#   (b) dampens the diurnal amplitude of the mean profile (winter+summer
#       average flatter than either season alone).
#
# Fix: write  L(t) = S(t) + R(t)  where S is a smooth annual baseline
# (low-pass) and R is the week-to-week residual.  Fit LW to R only, sample
# R stochastically, and add back the deterministic S(t) at the target week.
# ─────────────────────────────────────────────────────────────────────────────
def smooth_seasonal_baseline(
    y: np.ndarray,
    window_days: int = 14,
    mode: str = "diurnal",
) -> np.ndarray:
    """
    Compute a slowly-varying baseline S(t) that removes annual drift.

    Two modes:

    * mode="daily" — take the daily mean, smooth with a centered moving
      average of `window_days`, broadcast back to hourly resolution.
      Removes seasonal level drift but assigns the *same* value to all
      hours of a day, so the residual R = L - S still carries the diurnal
      cycle.  This means the LW mean_ has to represent the diurnal cycle,
      which is dampened to the annual average and doesn't adapt to season.

    * mode="diurnal" (default) — smooth per hour-of-day. For each of the
      24 hours, a centered moving average across the `window_days`
      neighbouring days gives the seasonally-local mean for that hour.
      The baseline thus has *both* seasonal level AND season-appropriate
      diurnal amplitude.  The LW residual is then almost pure stochastic
      week-to-week noise, not a mixture of seasonal shape + noise.
    """
    T = y.size
    assert T % 24 == 0, f"expected multiple of 24 hours, got {T}"
    days = T // 24
    half = window_days // 2
    kernel = np.ones(2 * half + 1) / (2 * half + 1)

    if mode == "daily":
        daily_mean = y.reshape(days, 24).mean(axis=1)
        padded = np.pad(daily_mean, half, mode="edge")
        smooth_daily = np.convolve(padded, kernel, mode="valid")
        return np.repeat(smooth_daily, 24)

    elif mode == "diurnal":
        L2d = y.reshape(days, 24)                              # (days, 24)
        padded = np.pad(L2d, ((half, half), (0, 0)), mode="edge")
        S2d = np.empty_like(L2d)
        for h in range(24):
            S2d[:, h] = np.convolve(padded[:, h], kernel, mode="valid")
        return S2d.reshape(-1)

    else:
        raise ValueError(f"unknown mode {mode!r}")


class SeasonalLedoitWolfEstimator:
    """
    Ledoit-Wolf shrinkage fit on the seasonally-adjusted residual.

    Fit:    R(t) = L(t) - S(t);   reshape R -> (168, n_weeks);   LW on R.
    Sample: L̂(t) = S(t) + R̂(t)   with R̂ drawn from LW on the residuals.

    The baseline S is stored at hourly resolution over the full training
    series, plus a per-week mean vector `season_per_week` so scenarios can
    be conditioned on *which* week of the year they represent.
    """

    def __init__(self, hours_per_sample: int = 168, window_days: int = 14):
        self.p = hours_per_sample
        self.window_days = window_days
        self.lw = LedoitWolfEstimator()

    def fit(self, y: np.ndarray) -> "SeasonalLedoitWolfEstimator":
        self.S_hourly = smooth_seasonal_baseline(y, window_days=self.window_days)
        R = y - self.S_hourly                            # (T,)
        self.R_weeks = reshape_to_weekly(R, self.p)      # (p, n_weeks)

        # Per-week baseline values (season context for each training week).
        S_weeks = reshape_to_weekly(self.S_hourly, self.p)  # (p, n_weeks)
        self.season_per_week = S_weeks.mean(axis=0)         # (n_weeks,)

        self.lw.fit(self.R_weeks)
        return self

    # ─── Sampling ─────────────────────────────────────────────────────────
    def sample(
        self,
        n_scenarios: int,
        target_week: int | None = None,
        seed: int | None = None,
    ) -> np.ndarray:
        """
        Return (p, n_scenarios) weekly scenarios.

        `target_week` selects which week of the training year the deterministic
        baseline S comes from (0 = first week of data). If None, the annual
        mean baseline is used (approximately what the flat LW would produce).
        """
        R_samples = self.lw.sample(n_scenarios, seed=seed)     # (p, S)
        Sw = reshape_to_weekly(self.S_hourly, self.p)            # (p, n_weeks)
        if target_week is None:
            S = Sw.mean(axis=1)                                  # annual avg
        else:
            target_week = target_week % Sw.shape[1]
            S = Sw[:, target_week]
        return S[:, None] + R_samples

    def sample_horizon(
        self,
        t_start: int,
        horizon: int,
        n_scenarios: int,
        seed: int | None = None,
    ) -> np.ndarray:
        """
        Scenarios over `horizon` hours starting at absolute training-time
        index `t_start`.  The baseline is taken exactly from that offset of
        the fitted S(t), so the seasonal level is correct for the call site.

        Returns (horizon, n_scenarios).
        """
        hour_of_week = t_start % self.p
        R_scen = self.lw.sample_horizon(hour_of_week, horizon, n_scenarios, seed=seed)
        # Deterministic baseline over the horizon — wraps if horizon goes
        # past the end of the training series.
        T = self.S_hourly.size
        idx = (t_start + np.arange(horizon)) % T
        S = self.S_hourly[idx]                           # (horizon,)
        return S[:, None] + R_scen


# ─────────────────────────────────────────────────────────────────────────────
# Empirical log-normal  — for FR capacity price π_f (Sec. IV.C)
# ─────────────────────────────────────────────────────────────────────────────
class EmpiricalLogNormalSampler:
    """
    Fits μ_log, σ_log from the empirical distribution of log(π_f) and samples
    π_f ~ exp(N(μ_log, σ_log²)).  Strictly positive and heavy-tailed, matching
    the paper's observation that FR price "has high variance".
    """

    def __init__(self, clip_quantile: float = 0.999):
        # Cap very extreme tail samples to avoid absurd $/kW outliers that
        # would destabilise the LP.  Set to 1.0 to disable.
        self.clip_quantile = clip_quantile

    def fit(self, x: np.ndarray) -> "EmpiricalLogNormalSampler":
        x = np.asarray(x, dtype=float)
        x = x[x > 0]                                  # log-normal needs positive support
        assert x.size > 2, "need at least 3 positive observations"
        logx = np.log(x)
        self.mu_log = float(logx.mean())
        self.sigma_log = float(logx.std(ddof=1))
        self.data_ = x
        # Convenience moments in original scale
        self.mean_ = float(np.exp(self.mu_log + 0.5 * self.sigma_log ** 2))
        self.median_ = float(np.exp(self.mu_log))
        self.var_ = float((np.exp(self.sigma_log ** 2) - 1.0)
                          * np.exp(2 * self.mu_log + self.sigma_log ** 2))
        self._clip_hi = (float(np.quantile(x, self.clip_quantile))
                         if self.clip_quantile < 1.0 else np.inf)
        return self

    def sample(self, shape, seed: int | None = None) -> np.ndarray:
        """Sample from the fitted log-normal. `shape` can be int or tuple."""
        rng = np.random.default_rng(seed)
        z = rng.standard_normal(size=shape)
        x = np.exp(self.mu_log + self.sigma_log * z)
        return np.minimum(x, self._clip_hi)


# ─────────────────────────────────────────────────────────────────────────────
# Empirical Gaussian  — for hourly FR signal α (Sec. IV.C)
# ─────────────────────────────────────────────────────────────────────────────
class EmpiricalGaussianSampler:
    """
    Fits μ, σ from the empirical distribution of α and samples iid N(μ, σ²).
    The paper notes α "approximately follows a Gaussian distribution, which
    indicates that there is small temporal correlation", so iid sampling is
    consistent with that modelling assumption.  Samples are clipped to the
    physical bound [-1, 1].
    """

    def fit(self, x: np.ndarray) -> "EmpiricalGaussianSampler":
        x = np.asarray(x, dtype=float)
        self.mu = float(x.mean())
        self.sigma = float(x.std(ddof=1))
        self.data_ = x
        return self

    def sample(self, shape, seed: int | None = None) -> np.ndarray:
        rng = np.random.default_rng(seed)
        z = rng.standard_normal(size=shape)
        return np.clip(self.mu + self.sigma * z, -1.0, 1.0)


# ─────────────────────────────────────────────────────────────────────────────
# Goodness-of-fit validation
# ─────────────────────────────────────────────────────────────────────────────
def validate_lognormal(x: np.ndarray, fit: EmpiricalLogNormalSampler) -> dict:
    """
    Tests that x is log-normal with the parameters in `fit`.

    Strategy: a variable is log-normal iff log(x) is normal.  We therefore
    run normality tests on the log-transformed data plus a K-S test against
    the fitted lognormal CDF.
    """
    logx = np.log(x[x > 0])

    # Shapiro-Wilk can only handle n <= 5000, so subsample if needed.
    rng = np.random.default_rng(0)
    sw_sample = logx if logx.size <= 5000 else rng.choice(logx, 5000, replace=False)
    sw_stat, sw_p = stats.shapiro(sw_sample)

    # Anderson-Darling — no sample-size limit; crit. values at 15/10/5/2.5/1%
    ad = stats.anderson(logx, dist="norm")

    # K-S against fitted lognormal in original scale
    ks = stats.kstest(x, "lognorm",
                      args=(fit.sigma_log, 0.0, np.exp(fit.mu_log)))

    return dict(
        n=int(x.size),
        skew_log=float(stats.skew(logx)),
        excess_kurt_log=float(stats.kurtosis(logx)),  # 0 = Gaussian
        shapiro_stat=float(sw_stat),
        shapiro_p=float(sw_p),
        ad_stat=float(ad.statistic),
        ad_crit_5pct=float(ad.critical_values[2]),    # 5% significance level
        ks_stat=float(ks.statistic),
        ks_p=float(ks.pvalue),
        fitted_mu_log=fit.mu_log,
        fitted_sigma_log=fit.sigma_log,
    )


def validate_gaussian(x: np.ndarray, fit: EmpiricalGaussianSampler) -> dict:
    """Same structure as above but testing x directly for normality."""
    rng = np.random.default_rng(0)
    sw_sample = x if x.size <= 5000 else rng.choice(x, 5000, replace=False)
    sw_stat, sw_p = stats.shapiro(sw_sample)
    ad = stats.anderson(x, dist="norm")
    ks = stats.kstest(x, "norm", args=(fit.mu, fit.sigma))
    return dict(
        n=int(x.size),
        skew=float(stats.skew(x)),
        excess_kurt=float(stats.kurtosis(x)),
        shapiro_stat=float(sw_stat),
        shapiro_p=float(sw_p),
        ad_stat=float(ad.statistic),
        ad_crit_5pct=float(ad.critical_values[2]),
        ks_stat=float(ks.statistic),
        ks_p=float(ks.pvalue),
        fitted_mu=fit.mu,
        fitted_sigma=fit.sigma,
    )


def _verdict(diag: dict, kind: str) -> str:
    """Plain-English read of the test battery."""
    ad_ok = diag["ad_stat"] < diag["ad_crit_5pct"]
    # K-S p > 0.05 → can't reject null that x follows fitted distribution
    ks_ok = diag["ks_p"] > 0.05
    skew = diag.get("skew_log" if kind == "log-normal" else "skew", 0.0)
    kurt = diag.get("excess_kurt_log" if kind == "log-normal" else "excess_kurt", 0.0)

    bits = []
    bits.append(f"K-S  {'PASS' if ks_ok else 'REJECT'} (p={diag['ks_p']:.3g})")
    bits.append(f"AD   {'PASS' if ad_ok else 'REJECT'} "
                f"({diag['ad_stat']:.2f} vs crit@5%={diag['ad_crit_5pct']:.2f})")
    bits.append(f"skew={skew:+.2f}, excess_kurt={kurt:+.2f}")
    return "  |  ".join(bits)


# ─────────────────────────────────────────────────────────────────────────────
# Demo: fit to real campus load and visualise samples against paper Fig. 5
# ─────────────────────────────────────────────────────────────────────────────
def _plot_fit(X: np.ndarray, est: LedoitWolfEstimator, scenarios: np.ndarray,
              out_path: str):
    p, n = X.shape
    hours = np.arange(p)
    fig, axs = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

    # Top — observed weekly profiles overlaid, with mean (Fig. 5 middle)
    for k in range(n):
        axs[0].plot(hours, X[:, k], color="steelblue", lw=0.6, alpha=0.35)
    axs[0].plot(hours, est.mean_, color="black", lw=2.0, label="Weekly mean profile")
    axs[0].set_ylabel("Load (kW)")
    axs[0].set_title(f"52 weekly load profiles + mean  (p={p}, n={n})")
    axs[0].legend(loc="upper right")
    axs[0].grid(alpha=0.3)

    # Bottom — sampled scenarios vs mean vs one held-out true week (Fig. 5 bottom)
    true_idx = 10
    for s in range(scenarios.shape[1]):
        axs[1].plot(hours, scenarios[:, s], color="tomato", lw=0.6, alpha=0.30)
    axs[1].plot(hours, est.mean_,   color="black", lw=2.0, label="Mean scenario")
    axs[1].plot(hours, X[:, true_idx], color="royalblue", lw=1.8, ls="--",
                label=f"True profile (week {true_idx})")
    axs[1].set_xlabel("Hour of week")
    axs[1].set_ylabel("Load (kW)")
    axs[1].set_title(f"{scenarios.shape[1]} Ledoit-Wolf scenarios  "
                     f"(shrinkage intensity = {est.shrinkage_intensity:.3f})")
    axs[1].legend(loc="upper right")
    axs[1].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(out_path, dpi=130)
    plt.close()


def _plot_scalar_fit(
    x: np.ndarray,
    samples: np.ndarray,
    pdf_fn,
    title: str,
    xlabel: str,
    out_path: str,
    logx: bool = False,
):
    """Histogram + fitted PDF + Q-Q plot, side-by-side."""
    fig, axs = plt.subplots(1, 2, figsize=(13, 4.5))

    # Left — histogram of data + fitted PDF + histogram of samples (dashed)
    bins = 60
    axs[0].hist(x, bins=bins, density=True, alpha=0.45, color="steelblue",
                label=f"data (n={x.size})")
    axs[0].hist(samples, bins=bins, density=True, histtype="step",
                color="tomato", lw=1.4, label=f"samples (n={samples.size})")
    xs = np.linspace(x.min(), x.max(), 400)
    axs[0].plot(xs, pdf_fn(xs), color="black", lw=2.0, label="fitted PDF")
    if logx:
        axs[0].set_xscale("log")
    axs[0].set_xlabel(xlabel); axs[0].set_ylabel("density")
    axs[0].set_title(title)
    axs[0].legend(loc="upper right", fontsize=9)
    axs[0].grid(alpha=0.3)

    # Right — Q-Q vs theoretical quantiles
    if logx:
        stats.probplot(np.log(x[x > 0]), dist="norm", plot=axs[1])
        axs[1].set_title("Q-Q plot of log(x) vs Normal")
    else:
        stats.probplot(x, dist="norm", plot=axs[1])
        axs[1].set_title("Q-Q plot of x vs Normal")
    axs[1].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(out_path, dpi=130)
    plt.close()


if __name__ == "__main__":
    ds = load_dataset()
    L = ds.L                                           # (8760,)
    X = reshape_to_weekly(L, hours_per_sample=168)     # (168, 52)
    print(f"Load reshaped: p={X.shape[0]} hrs/week × n={X.shape[1]} weeks")

    est = LedoitWolfEstimator().fit(X)

    print("\nLedoit-Wolf scalar estimators:")
    print(f"  m   (⟨S,I⟩)          = {est.m:.4e}  kW²")
    print(f"  d²  (||S - mI||²)    = {est.d2:.4e}")
    print(f"  b̄²  (raw)            = {est.b2_bar:.4e}")
    print(f"  b²  = min(b̄², d²)   = {est.b2:.4e}   (→ β²n)")
    print(f"  a²  = d² - b²        = {est.a2:.4e}   (→ α²n)")
    print(f"  shrinkage b²/d²      = {est.shrinkage_intensity:.4f}  "
          f"(0 = pure sample cov, 1 = identity target)")

    eigs = np.linalg.eigvalsh(est.Sigma)
    print(f"\nΣ̃n eigenvalues: min={eigs.min():.3e}, max={eigs.max():.3e}, "
          f"cond={eigs.max()/max(eigs.min(),1e-30):.2e}")

    # Draw scenarios
    scenarios = est.sample(n_scenarios=50, seed=0)
    print(f"\nSampled {scenarios.shape[1]} full-week scenarios, shape={scenarios.shape}")

    # Slice example for a stochastic-MPC horizon
    hour_of_week = 36          # e.g. Monday 12:00
    N = 24
    horizon_scenarios = est.sample_horizon(hour_of_week, N, n_scenarios=50, seed=1)
    print(f"Horizon-slice scenarios at hour_of_week={hour_of_week}, N={N}: "
          f"shape={horizon_scenarios.shape}")

    # Plot fit + samples (flat LW)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "ledoit_wolf_load.png")
    _plot_fit(X, est, scenarios, out)
    print(f"\nPlot saved -> {out}")

    # ─────────────────────────────────────────────────────────────────────
    # Seasonally-adjusted LW — compare against flat LW
    # ─────────────────────────────────────────────────────────────────────
    print("\n" + "=" * 72)
    print("LOAD — Seasonally-adjusted Ledoit-Wolf")
    print("=" * 72)
    sest = SeasonalLedoitWolfEstimator(hours_per_sample=168, window_days=14).fit(L)
    print(f"  baseline window      : {sest.window_days} days")
    print(f"  season range         : {sest.season_per_week.min():.0f} → "
          f"{sest.season_per_week.max():.0f} kW  "
          f"(flat LW swallowed this as noise)")
    print(f"  residual mean        : {sest.R_weeks.mean():+.0f} kW   "
          f"(≈ 0 by construction)")
    print(f"  residual std         : {sest.R_weeks.std():.0f} kW   "
          f"(vs raw weekly std {X.std():.0f})")

    eigs_s = np.linalg.eigvalsh(sest.lw.Sigma)
    flat_per_hr = np.sqrt(np.trace(est.Sigma) / 168)
    seas_per_hr = np.sqrt(np.trace(sest.lw.Sigma) / 168)
    print(f"  LW on residual:")
    print(f"    shrinkage intensity = {sest.lw.shrinkage_intensity:.4f}   "
          f"(flat LW = {est.shrinkage_intensity:.4f})")
    print(f"    top eigenvalue      = {eigs_s[-1]:.2e}   "
          f"(flat LW top = {eigs[-1]:.2e})")
    print(f"    per-hr implied std  = {seas_per_hr:.0f} kW   "
          f"(flat LW = {flat_per_hr:.0f} kW)")

    # Helper: lag-1 autocorrelation of a 1-D sequence
    def _lag1_ac(y):
        y = np.asarray(y, dtype=float)
        y = y - y.mean()
        denom = (y * y).sum()
        if denom <= 0:
            return 0.0
        return float((y[:-1] * y[1:]).sum() / denom)

    # Helper: diurnal amplitude = mean(peak-of-day) - mean(trough-of-day)
    def _diurnal_amp(y, p=168):
        d = y.reshape(-1, 24)                   # (7 days, 24 hrs) within a week
        return float(d.max(axis=1).mean() - d.min(axis=1).mean())

    # Compare sampled variability, periodicity (lag-1 AC), and diurnal amplitude
    # to real weeks. These quantify the three complaints: (1) variance too high,
    # (2) no periodicity, (3) no seasonal adaptation.
    print(f"\n  {'week':>5s}  {'real_std':>9s}  {'samp_std':>9s}   "
          f"{'real_AC1':>9s}  {'samp_AC1':>9s}   "
          f"{'real_amp':>9s}  {'samp_amp':>9s}")
    for wk in [10, 30]:
        real_week = X[:, wk]
        scen_wk = sest.sample(n_scenarios=200, target_week=wk, seed=42)   # (168, 200)
        samp_std = scen_wk.std(axis=0).mean()
        samp_ac  = np.mean([_lag1_ac(scen_wk[:, s]) for s in range(scen_wk.shape[1])])
        samp_amp = np.mean([_diurnal_amp(scen_wk[:, s]) for s in range(scen_wk.shape[1])])
        print(f"  {wk:5d}  {real_week.std():>9.0f}  {samp_std:>9.0f}   "
              f"{_lag1_ac(real_week):>9.3f}  {samp_ac:>9.3f}   "
              f"{_diurnal_amp(real_week):>9.0f}  {samp_amp:>9.0f}")

    # Flat LW baseline for the same metrics — reference point for comparison.
    flat_scen = est.sample(n_scenarios=200, seed=42)
    flat_std  = flat_scen.std(axis=0).mean()
    flat_ac   = np.mean([_lag1_ac(flat_scen[:, s]) for s in range(flat_scen.shape[1])])
    flat_amp  = np.mean([_diurnal_amp(flat_scen[:, s]) for s in range(flat_scen.shape[1])])
    print(f"  flat   {'':>9s}  {flat_std:>9.0f}   "
          f"{'':>9s}  {flat_ac:>9.3f}   {'':>9s}  {flat_amp:>9.0f}")

    # ─────────────────────────────────────────────────────────────────────
    # Diagnostic: daily framing (p=24, n=365) — does more data help LW?
    # ─────────────────────────────────────────────────────────────────────
    # p=168, n=52 is p>n, so LW is *forced* to shrink heavily (0.63 here)
    # toward the identity target, killing lag-1 autocorrelation.  Daily
    # framing is p<n so LW keeps more of the sample covariance, which is
    # the direct test of the "not enough data" hypothesis.
    print("\n  Alternative framing  (p=24 days, n=365)  —  'is there enough data?'")
    sest_d = SeasonalLedoitWolfEstimator(hours_per_sample=24, window_days=14).fit(L)
    print(f"    shrinkage intensity = {sest_d.lw.shrinkage_intensity:.4f}   "
          f"(weekly was {sest.lw.shrinkage_intensity:.4f})")
    print(f"    residual std        = {sest_d.R_weeks.std():.0f} kW   "
          f"(weekly was {sest.R_weeks.std():.0f})")

    # Build a 7-day week by drawing 7 independent daily scenarios from the
    # 7 consecutive days of the target week.  Each day uses its own correct
    # seasonal baseline, so the concatenated week has the right seasonal shape.
    for wk in [10, 30]:
        rng = np.random.default_rng(42)
        days = []
        for d in range(7):
            target_day = wk * 7 + d
            day_scen = sest_d.sample(n_scenarios=200,
                                     target_week=target_day,
                                     seed=int(rng.integers(1 << 30)))     # (24, 200)
            days.append(day_scen)
        week_scen = np.concatenate(days, axis=0)                           # (168, 200)
        real_week = X[:, wk]
        samp_std = week_scen.std(axis=0).mean()
        samp_ac  = np.mean([_lag1_ac(week_scen[:, s]) for s in range(week_scen.shape[1])])
        samp_amp = np.mean([_diurnal_amp(week_scen[:, s]) for s in range(week_scen.shape[1])])
        print(f"    week {wk:2d}: real_std={real_week.std():.0f}  "
              f"samp_std={samp_std:.0f}   "
              f"real_AC1={_lag1_ac(real_week):.2f}  samp_AC1={samp_ac:.2f}   "
              f"real_amp={_diurnal_amp(real_week):.0f}  samp_amp={samp_amp:.0f}")

    # ─────────────────────────────────────────────────────────────────────
    # Diagnosis summary
    # ─────────────────────────────────────────────────────────────────────
    print("""
  ── Why LW underperforms on this load ─────────────────────────────────
    (1) Seasonal drift  →  FIXED by L(t) = S(t) + R(t) with diurnal baseline.
        Top eigenvalue 4.68e8 → 1.69e7 (25× smaller "annual shift" mode).
        Scenarios now sit at the correct winter/summer level.
    (2) Variance inflation  →  REDUCED ~20% (per-hr std 2221 → 1385 kW)
        by moving the deterministic diurnal shape out of the covariance.
    (3) Lost temporal correlation (lag-1 AC)  →  REMAINING LIMITATION.
        Weekly framing p=168, n=52 forces LW to shrink 65% toward identity
        (white noise), destroying hour-to-hour autocorrelation.
        Root cause: "not enough data" — confirmed by p=24, n=365 framing
        where shrinkage drops 0.65 → 0.08.  With 52 weekly samples of a
        strongly autocorrelated load, LW *has* to discard structure to stay
        numerically well-conditioned.  Mitigations: (a) use daily p=24
        framing for 24-h MPC horizon, (b) fit ARMA/AR(1) on residual, or
        (c) gather more years of data.""")

    # Plot: show that week-10 and week-30 samples now land on their own season
    scen_w10 = sest.sample(n_scenarios=50, target_week=10, seed=1)
    scen_w30 = sest.sample(n_scenarios=50, target_week=30, seed=2)
    fig, axs = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
    hours = np.arange(168)

    for sc in range(scen_w10.shape[1]):
        axs[0].plot(hours, scen_w10[:, sc], color="steelblue", lw=0.6, alpha=0.3)
    axs[0].plot(hours, X[:, 10], color="black", lw=2.0, label="Week 10 true")
    axs[0].plot(hours, scen_w10.mean(axis=1), color="royalblue", lw=1.5,
                ls="--", label="Week 10 sample mean")
    axs[0].set_title("Seasonally-adjusted LW — 50 scenarios for Week 10 (cold season)")
    axs[0].set_ylabel("Load (kW)"); axs[0].legend(); axs[0].grid(alpha=0.3)
    axs[0].set_ylim(X.min() - 500, X.max() + 500)

    for sc in range(scen_w30.shape[1]):
        axs[1].plot(hours, scen_w30[:, sc], color="tomato", lw=0.6, alpha=0.3)
    axs[1].plot(hours, X[:, 30], color="black", lw=2.0, label="Week 30 true")
    axs[1].plot(hours, scen_w30.mean(axis=1), color="crimson", lw=1.5,
                ls="--", label="Week 30 sample mean")
    axs[1].set_title("Seasonally-adjusted LW — 50 scenarios for Week 30 (warm season)")
    axs[1].set_xlabel("Hour of week"); axs[1].set_ylabel("Load (kW)")
    axs[1].legend(); axs[1].grid(alpha=0.3)
    axs[1].set_ylim(X.min() - 500, X.max() + 500)

    plt.tight_layout()
    out_s = os.path.join(root, "ledoit_wolf_load_seasonal.png")
    plt.savefig(out_s, dpi=130); plt.close()
    print(f"  plot saved -> {out_s}")

    # ─────────────────────────────────────────────────────────────────────
    # Energy price π_e — flat LW + seasonally-adjusted LW
    # ─────────────────────────────────────────────────────────────────────
    # NYISO LMP has the same structure as load: strong diurnal cycle
    # (morning/evening peak pricing), weekly pattern (weekday vs weekend),
    # and seasonal drift (summer heat-wave spikes).  Same LW machinery
    # applies — we just swap the input series.
    print("\n" + "=" * 72)
    print("ENERGY PRICE (π_e) — Ledoit-Wolf (flat + seasonally-adjusted)")
    print("=" * 72)
    pi_e = ds.pi_e                                          # (8760,) $/kWh
    Xp = reshape_to_weekly(pi_e, hours_per_sample=168)      # (168, 52)
    print(f"  π_e series: mean={pi_e.mean():.4f} $/kWh  "
          f"std={pi_e.std():.4f}  "
          f"min={pi_e.min():.4f}  max={pi_e.max():.4f}")

    pest = LedoitWolfEstimator().fit(Xp)
    print(f"\n  Flat LW (p=168, n=52):")
    print(f"    shrinkage intensity = {pest.shrinkage_intensity:.4f}")
    eigs_p = np.linalg.eigvalsh(pest.Sigma)
    print(f"    eigenvalues: min={eigs_p.min():.3e}  max={eigs_p.max():.3e}  "
          f"cond={eigs_p.max()/max(eigs_p.min(),1e-30):.2e}")
    print(f"    per-hr implied std  = {np.sqrt(np.trace(pest.Sigma)/168):.4f} $/kWh")

    pseas = SeasonalLedoitWolfEstimator(hours_per_sample=168, window_days=14).fit(pi_e)
    eigs_ps = np.linalg.eigvalsh(pseas.lw.Sigma)
    print(f"\n  Seasonal LW (baseline window = {pseas.window_days} days):")
    print(f"    season range        : {pseas.season_per_week.min():.4f} → "
          f"{pseas.season_per_week.max():.4f} $/kWh")
    print(f"    residual std        : {pseas.R_weeks.std():.4f} $/kWh   "
          f"(vs raw weekly std {Xp.std():.4f})")
    print(f"    shrinkage intensity = {pseas.lw.shrinkage_intensity:.4f}   "
          f"(flat LW = {pest.shrinkage_intensity:.4f})")
    print(f"    top eigenvalue      = {eigs_ps[-1]:.3e}   "
          f"(flat LW top = {eigs_p[-1]:.3e})")
    print(f"    per-hr implied std  = {np.sqrt(np.trace(pseas.lw.Sigma)/168):.4f} "
          f"$/kWh")

    # Scenario diagnostics for a winter week and a summer week
    print(f"\n  {'week':>5s}  {'real_std':>9s}  {'samp_std':>9s}   "
          f"{'real_AC1':>9s}  {'samp_AC1':>9s}   "
          f"{'real_amp':>9s}  {'samp_amp':>9s}")
    for wk in [10, 30]:
        real_week = Xp[:, wk]
        scen_wk = pseas.sample(n_scenarios=200, target_week=wk, seed=42)
        samp_std = scen_wk.std(axis=0).mean()
        samp_ac  = np.mean([_lag1_ac(scen_wk[:, s]) for s in range(scen_wk.shape[1])])
        samp_amp = np.mean([_diurnal_amp(scen_wk[:, s]) for s in range(scen_wk.shape[1])])
        print(f"  {wk:5d}  {real_week.std():>9.4f}  {samp_std:>9.4f}   "
              f"{_lag1_ac(real_week):>9.3f}  {samp_ac:>9.3f}   "
              f"{_diurnal_amp(real_week):>9.4f}  {samp_amp:>9.4f}")

    # Plot seasonally-adjusted scenarios for two contrasting weeks
    scen_pe_w10 = pseas.sample(n_scenarios=50, target_week=10, seed=1)
    scen_pe_w30 = pseas.sample(n_scenarios=50, target_week=30, seed=2)
    fig, axs = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
    hours = np.arange(168)
    ymin = min(Xp.min(), scen_pe_w10.min(), scen_pe_w30.min()) - 0.005
    ymax = max(Xp.max(), scen_pe_w10.max(), scen_pe_w30.max()) + 0.005

    for sc in range(scen_pe_w10.shape[1]):
        axs[0].plot(hours, scen_pe_w10[:, sc], color="steelblue", lw=0.6, alpha=0.3)
    axs[0].plot(hours, Xp[:, 10], color="black", lw=2.0, label="Week 10 true")
    axs[0].plot(hours, scen_pe_w10.mean(axis=1), color="royalblue", lw=1.5,
                ls="--", label="Week 10 sample mean")
    axs[0].set_title("Energy price π_e — Seasonal LW, 50 scenarios, Week 10 (cold)")
    axs[0].set_ylabel("π_e  [$/kWh]"); axs[0].legend(); axs[0].grid(alpha=0.3)
    axs[0].set_ylim(ymin, ymax)

    for sc in range(scen_pe_w30.shape[1]):
        axs[1].plot(hours, scen_pe_w30[:, sc], color="tomato", lw=0.6, alpha=0.3)
    axs[1].plot(hours, Xp[:, 30], color="black", lw=2.0, label="Week 30 true")
    axs[1].plot(hours, scen_pe_w30.mean(axis=1), color="crimson", lw=1.5,
                ls="--", label="Week 30 sample mean")
    axs[1].set_title("Energy price π_e — Seasonal LW, 50 scenarios, Week 30 (warm)")
    axs[1].set_xlabel("Hour of week"); axs[1].set_ylabel("π_e  [$/kWh]")
    axs[1].legend(); axs[1].grid(alpha=0.3)
    axs[1].set_ylim(ymin, ymax)

    plt.tight_layout()
    out_pe = os.path.join(root, "ledoit_wolf_energy_price.png")
    plt.savefig(out_pe, dpi=130); plt.close()
    print(f"  plot saved -> {out_pe}")

    # ─────────────────────────────────────────────────────────────────────
    # FR price:  empirical log-normal
    # ─────────────────────────────────────────────────────────────────────
    print("\n" + "=" * 72)
    print("FR PRICE (π_f) — empirical log-normal")
    print("=" * 72)
    pi_f = ds.pi_f                                        # $/kW-h
    lognorm_fit = EmpiricalLogNormalSampler().fit(pi_f)
    print(f"  fit: μ_log = {lognorm_fit.mu_log:+.4f}  "
          f"σ_log = {lognorm_fit.sigma_log:.4f}")
    print(f"       implied mean  = {lognorm_fit.mean_:.5f}  "
          f"(empirical mean = {pi_f.mean():.5f})")
    print(f"       implied median= {lognorm_fit.median_:.5f}  "
          f"(empirical median = {np.median(pi_f):.5f})")
    print(f"       implied var   = {lognorm_fit.var_:.3e}  "
          f"(empirical var = {pi_f.var():.3e})")

    diag_pf = validate_lognormal(pi_f, lognorm_fit)
    print(f"  validation: {_verdict(diag_pf, 'log-normal')}")
    print(f"  Shapiro-Wilk on log(π_f):  W={diag_pf['shapiro_stat']:.4f}  "
          f"p={diag_pf['shapiro_p']:.3g}")

    pf_samples = lognorm_fit.sample(shape=pi_f.size, seed=0)
    print(f"  drew {pf_samples.size} samples  "
          f"(mean={pf_samples.mean():.5f}, std={pf_samples.std():.5f})")

    def _lognorm_pdf(xv):
        return stats.lognorm.pdf(xv, lognorm_fit.sigma_log, loc=0.0,
                                 scale=np.exp(lognorm_fit.mu_log))
    out_pf = os.path.join(root, "fr_price_lognormal.png")
    _plot_scalar_fit(pi_f, pf_samples, _lognorm_pdf,
                     title="FR price π_f — empirical log-normal",
                     xlabel="π_f  [$/kW-h]",
                     out_path=out_pf, logx=True)
    print(f"  plot saved -> {out_pf}")

    # ─────────────────────────────────────────────────────────────────────
    # FR signal:  empirical Gaussian
    # ─────────────────────────────────────────────────────────────────────
    print("\n" + "=" * 72)
    print("FR SIGNAL (α) — empirical Gaussian")
    print("=" * 72)
    alpha = ds.alpha
    gauss_fit = EmpiricalGaussianSampler().fit(alpha)
    print(f"  fit: μ = {gauss_fit.mu:+.4f}  σ = {gauss_fit.sigma:.4f}")

    diag_a = validate_gaussian(alpha, gauss_fit)
    print(f"  validation: {_verdict(diag_a, 'gaussian')}")
    print(f"  Shapiro-Wilk on α:         W={diag_a['shapiro_stat']:.4f}  "
          f"p={diag_a['shapiro_p']:.3g}")

    a_samples = gauss_fit.sample(shape=alpha.size, seed=0)
    print(f"  drew {a_samples.size} samples  "
          f"(mean={a_samples.mean():+.4f}, std={a_samples.std():.4f})")

    def _norm_pdf(xv):
        return stats.norm.pdf(xv, loc=gauss_fit.mu, scale=gauss_fit.sigma)
    out_a = os.path.join(root, "fr_signal_gaussian.png")
    _plot_scalar_fit(alpha, a_samples, _norm_pdf,
                     title="FR signal α — empirical Gaussian",
                     xlabel="α  [-]",
                     out_path=out_a, logx=False)
    print(f"  plot saved -> {out_a}")
